# permissions for end users to view vclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcluster-viewer-role
rules:
- apiGroups:
  - nasermirzaei89.net
  resources:
  - vclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nasermirzaei89.net
  resources:
  - vclusters/status
  verbs:
  - get
